# Generated by Django 3.1 on 2021-06-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
