# Generated by Django 3.1 on 2021-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username1',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
