# Generated by Django 3.1 on 2021-06-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username1',
        ),
    ]
