# Generated by Django 3.1 on 2021-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
