# Generated by Django 3.1 on 2021-10-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20211004_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
    ]
