# Generated by Django 3.1 on 2021-06-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210617_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingadd',
            new_name='shippingaddress',
        ),
    ]
