# Generated by Django 3.1 on 2021-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210618_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
