# Generated by Django 3.1 on 2021-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_shipcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipCost',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=10, null=True),
        ),
    ]
