# Generated by Django 3.1 on 2021-06-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210619_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipCost',
        ),
    ]
