# Generated by Django 3.1 on 2021-10-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20211001_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress',
        ),
    ]
